# fiki — Intent Tree (this.i)
#
# The source of truth for why this repo is built the way it is. Code and docs/ are derived from
# it; every consequential decision lands here first, in its own commit, before the code it
# justifies. See bakobo/dev/methodology.md for the rules and AGENTS.md for this repo's stanza.
#
# Nodes are written with the `i` CLI (`i add <type> "<name>" --parent <nid> --why "..."`), which
# mints the ids. Never hand-type an id.
#
# fiki was carved out of bakobo/heti; the decision to split lives in heti's tree at @3qewrm0p,
# with @m4x7rc above it as the packaging decision it revisits. Nodes here cite those by id.

fiki proves which key sent an HTTP request, with no KERI stack on either end = goal:
  nid: 07wstqk7
  why: >-
    fiki lets a party with no KERI stack prove which key sent an HTTP request, and lets a Bakobo service check that proof. It is standard RFC 9421 with one lens: a bare Ed25519 public key is rendered as a non-transferable AID (CESR Ed25519N, a 44-character "B..." string), so the identifier IS the verifying key and a verifier needs no key event log, no directory lookup, and no network call to recover it. A client registers its AID once and signs from then on; there is nothing to rotate and nothing to fetch. Chose to carve this out of bakobo/heti (heti @m4x7rc, @3qewrm0p) rather than tell such a party to install heti, because heti reaches KERI through keripy and keripy brings 24 direct dependencies including lmdb, pysodium, falcon, and hio -- an unreasonable price for an ESB client, a cron job, or a container that only needs to say who it is. fiki depends on cryptography and http_sfv and on nothing else, so it must never import keripy and must never import bakobo-errors (@8zw78n0v); heti maps fiki's exceptions onto its own codes at the boundary. Chose the standards-vanilla dialect over the KERI flavor keria and signify-ts speak, because that flavor's signature base diverges from RFC 9421 in three ways and porting it to another language means reimplementing those divergences forever, whereas vanilla means "your language's RFC 9421 library plus a 40-line AID codec." Rejected making this a subpackage of heti behind an import boundary, which is what heti @m4x7rc chose in the first place and explicitly named its own falsifier for: a code boundary buys no smaller dependency tree, and the footprint is the entire point here. Rejected a repo per language, because the conformance vectors would fork. Tradeoff: fiki cannot talk to keria or to anything else speaking the KERI flavor, and a Bakobo service that wants to accept both dialects has to run both libraries.
  children:
    The default covered set closes the query, host, and body gaps, and fails closed = decision:
      nid: 2hwvpm42
      why: >-
        fiki's default covered set is @method, @authority, @path, @query, and created, plus a Content-Digest whenever the request carries a body. Signing a request that has a body and no Content-Digest RAISES rather than proceeding, and on the verify side fiki recomputes the digest over the received body and rejects a mismatch instead of trusting the header because the signature covers it. Chose this over heti's inherited set (Signify-Resource, @method, @path, Signify-Timestamp) because that set covers neither the query string, the host, nor the body: RFC 9421 has @path stop at the question mark, so a signed GET /things?limit=1 is indistinguishable from ?limit=1000000, and a POST body can be swapped wholesale. That is structural in the KERI dialect -- keripy's ending.siginput has no else branch for other derived components, which heti @h4s6tz books as its standing tradeoff and which is the subject of WebOfTrust/keripy#1669 -- and fiki is not under that ceiling, so it does not inherit the hole. Chose to refuse an unsigned body rather than warn, because a signing-side warning is read by nobody and a verifier cannot discover after the fact that the body was never covered; fail closed is the org's eighth principle. Chose to recompute the digest rather than verify the signature alone, for the same reason: a covered Content-Digest attests to a body nobody hashed, which is a guarantee about a header rather than about the request. Rejected covering @target-uri instead of the @authority/@path/@query trio: it binds the scheme, which a client behind a TLS-terminating proxy cannot reproduce. Rejected a caller opt-out on digest recomputation for streaming verifiers, because an opt-out is where fail-open returns; a streaming verifier is a real case and it can have a decision of its own later. Tradeoff: verification needs the whole body in memory, so fiki cannot verify a streamed request, and a fiki-signed request is not verifiable by heti's KERI path at all because the covered sets do not overlap -- the dialect is a deployment-time choice rather than a fallback chain.
    fiki raises its own exceptions and depends on no Bakobo error package = decision:
      nid: 8zw78n0v
      why: >-
        fiki raises its own exceptions and depends on no Bakobo error package. A small closed set of classes descends from one base, so a consumer can catch the base or discriminate by type, and heti maps each class onto its existing e.input.* and e.proof.* codes at the boundary with a test that walks the base class's subclasses and fails if any class has no mapping. Chose fiki-owned exceptions over depending on bakobo-errors because a dependency that travels into every language port is a dependency every port has to reimplement, and the point of the split is a library a cron job can install; bakobo-errors would also export Bakobo's sorter/descriptor/disposition grammar and its house voice into Go and JS, where none of it is wanted. Chose class-based discrimination over an error-code string attribute because the totality test then has a mechanical subject -- __subclasses__ -- rather than a registry someone must remember to update. Rejected heti catching a single fiki base exception and raising one generic code, which would collapse the taxonomy heti @x2r7mv built deliberately. Tradeoff: two vocabularies for the same failures, and the plain-sentence titles Bakobo's error standard requires live only on heti's side, so a caller using fiki directly gets a worse message than a caller reaching it through heti.
    Two conformance oracles — RFC 9421's own vectors, plus one committed Bakobo vector set = decision:
      nid: 5gf6r08f
      why: >-
        fiki's conformance rests on two oracles, and the repo is laid out so they cannot fork. RFC 9421's own Appendix B vectors come first, and they are usable on the SIGNING side rather than only for verification, because Appendix B.1.4 publishes the Ed25519 private key (PEM, and as a JWK with d = n4Ni-HpISpVObnQMW0wOhCKROaIKqKtW_2ZYb2p9KcU) and Ed25519 is deterministic with created pinned at 1618884473 -- so signing B.2.6's request reproduces the RFC's own Signature header byte for byte. Chose that as the first test written and the first test run red, because no Bakobo party authored it and it fails for a reason we cannot argue with. Verified 2026-09-03 against the RFC text itself rather than a summary: a WebFetch of the same appendix returned a fabricated public key and a fabricated B.2.6 component list, both plausible and both wrong, so no byte-exact value in this repo is ever taken from a summarizing tool. The second oracle is a committed vectors/ set at the repo root for what the RFC cannot cover, which is more than it sounds: B.2.6 exercises neither @query nor content-digest, and its own test request carries a query string it does not sign, so the two protections @2hwvpm42 adds beyond heti have NO RFC oracle and the Bakobo vectors are the only thing standing behind them. The vectors also carry the AID lens (a 32-byte Ed25519 key to a B-prefix non-transferable AID and back) and the refuse-a-body-without-Content-Digest rule. The polyglot layout -- py/, later go/ and js/, over one top-level vectors/ -- exists for exactly this reason rather than for tidiness: a repo per language would give each port its own copy of the vectors to age independently. Rejected generating the Bakobo vectors from keripy, which would reintroduce the dependency this repo exists to remove and would pin fiki to a reference that is not the standard; the AID codec is instead cross-checked against keripy inside HETI's suite, where keripy is present anyway, and byte-equality there is what keeps fiki's key type and heti's EphemeralKey interchangeable over one seed. Rejected deferring the vectors until a second language actually exists, because they are the only thing that makes a port checkable and a hand-port without them is a fork with a delay on it. Tradeoff: py/ carries a directory level nothing needs today, and the vectors must be regenerated deliberately when the default covered set changes, with nothing gating that -- so each vector file names the covered set it was generated under rather than relying on anyone to remember.
    The key travels inline in keyid, as raw bytes rather than as the AID = decision:
      nid: 7xrx5evg
      why: >-
        The signer's key travels in RFC 9421's own keyid parameter, as the RAW 32-byte Ed25519 public key in base64url with no padding -- the RFC 8037 JWK "x" form, 43 characters -- and NOT as the 44-character B-prefix AID. So a request carries its own verifying key inline and a verifier resolves nothing; the AID remains what a human registers and reads, and fiki derives it from the keyid on the verify side rather than transmitting it. This is not a fresh choice: heti's vanilla dialect already fixes it at src/heti/ephemeral/vanilla.py:_resolve_key, whose @c3m5wp chose the inline raw-key form over a directory lookup because both of its recovery paths must stay pure, and cited draft-hardt-httpbis-signature-key and Cloudflare's web-bot-auth as the external convention. fiki emitting the AID there instead would mean heti could not verify a fiki-signed request at all, which would defeat the interop the split exists to preserve, so the decision is inherited rather than reopened. Chose one form rather than accepting both, because a keyid a verifier has to sniff is an interop ambiguity that shows up as a signature failure at somebody else's site. Chose to keep sign_request's keyid NON-overridable, unlike the lower-level signature_base, so that "the keyid is the key" is a property of every fiki-signed request rather than a default: the RFC's own Appendix B.2.6 vector uses a symbolic keyid ("test-key-ed25519") and is reproduced through signature_base for exactly that reason. Rejected carrying the AID in a separate header the way the KERI dialect carries Signify-Resource, which would put the identity outside RFC 9421's own vocabulary and give an off-the-shelf verifier one more thing it does not implement. Tradeoff: a verifier holding a preregistered AID must convert it to raw bytes to compare against keyid, which is two lines but is a conversion that would not exist if the AID travelled directly; and a fiki-signed request is pseudonymous by construction, since an inline key attests to itself and to nothing else.
